language: java

jdk:
  - oraclejdk8

services:
  - mysql

before_script:
  - cp travis.properties config.properties
  - mysql -e 'create database movies_test_db;'
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B
